var htmlConfig = {
  bookConfig:
    "v010001103114KXk6Keg4GWgyEWk5GSjzOVvzHVm9DSguHUsxDQqvIas9BTiyNdkuNYu1OUv5OSs1NRmyMZo1JQpuAXqwGXn9Jct1AdtyCSlvFas2ITvzFXmuCQn0KZr8PZj1ORo8PdjyHUr0Ibn8DfovMXg5CWi1NXp5GSj2FUk1DbruKZh2Afi5BQh1GWt1OUn0AZt9GWt5NSsvIUv2ATn2IVv4MZkwIRr2BdlyGTk4DUt1PfozBVjyIYqzBSn7Jes9Kbm3Kbv8OcruKTo8Pbm2Iav6LQh3IXj9PVswAdq5BTl0AUtyIWizGRj3LUmyOSs7FZo0ORsuMevzKZj4PQj8KSq5HVn3NZizGcr6NUoyAWr5MUhuNTk3Lap8ESv6KXo9HdnxHTs9NZmyGch0Fbi4MchwAXjyMYjxJTt6AbowIfq8MRr8LVi0LYg5ObozCQh3MZhzJSl5Heq6NQkxIQv6IThwIbg1KUovOcn8NTqxDQrxHftwGRm6KVjxDWkxPTkzLXj7AfquDVn5LcswBZkvEUozLVq7FSrzAZg6FTm5DWh0FRkvIXn1Afk2Oas9CaswFVg2JYhxOau4HXlvIUouGXrwCVm8Mcm2BfhzBUlxCRg0FQiyMQl1Lfk0FRt9PQk7EWg2NQgzFTjuIWn4KXjxFcq2LWv2ERm6JWg8Jcs2ParvBSi1KXpzKYu2PQo0ATp2Pdm6OStyEZryNau3CfluDdt6JenuNVk9LSi8FSuuDYj2HQs2CSkyLau6NfryAXswBRqxAdlvNZvvNdowGUh7HSq7Ldq8Heg2LUu4LQu1BRj8MWowHakuJXj3Fep6Ffq4Jbo4OSq2HSg3HQpxIRrwIZkwPXtxERq9KTk0BTj7JQuvJXl2DWmxAUh1CYq8FVt4NVr1BbgxCWm1BSu3JYh5GYm9Odg6DQgvLasvMUmyKQs3DSs2AcpwHSt4NTqzFUtvFRs8Gep6DRo0Dam3HRj1FQl6Pam8Mdo7MRo3FRj2Jcp0ESv8DXp6GVh8Fdp3GXv5Hcs1Cbp0JUu1MYjuARpxEXt0GVp0BSl4ESuwKYoxGQm7Odj5FcmxCYj2LZpxGSlyKZvvKdt8Net1ITr1EVu9CfnwEUu3Hao5FfmyJVj5JYr9FRv0Ebk1PZq3Hcn1MXgzDXu5LTnxKRi0KVi3Jeh8Gbm6BTv9Gen5GXg1Ibl9HQjvLeo8AZk6Oah2IWizBXo2DSkuLWo6LcuyEfgyCTg1ARpzFdr8Lcr3Mau3CQu8JbvvJYu6NenvFal6GXk8Oco7IcixMZgzEerxHco0Bdi7GSs4AWgzAQlyLXlyIZjuKYluCbk7GUizOWu9CeswDas5DetwMdu2Nbv3Lcn3PUl8FXn5BUr7Mcp4GQhzPTjvDTl6GeszHRv9PUryGbv6Kcq0BRhuLSo0Cao2LRnxDRkzJRtyCdo6EbowIXgwOSrzOfpyFdu8HRozLVo9MVt5IWmxEZtwAdm8FWhxOfq3JaqwAQvzAZg2BQhuDeq4BXhvOUv8Aei4EQn5Acj8Iag8PTo8MTq9Adg3NdtzISk9ISl9Oag6LQqzNSs8NYu2HRh2OfpzEftuFSs3DWl8Peo8OcrzGRl5IZsyGRryBao1DVn7CWtwPYq9PdsyOYq5IVvwCVovLRg0Nbs5KSk4OQpwCXlwIXtyMYq2Gcp8Jdu3KVp2Feg8Nco6KXs7GahwDVmuMcvvNbh4EZvvCVn6Pbm2PUt8BUj5HXo5Kcn4GZkwDQs5NfrvLZq1IdgzIUl9FUt9Oft0OWpwHVk5Nbo5Oan1PXj1GRv9CQmuGYn6NWtvAQqyJci3Oen8Dfj1JcsyFYs7MbuwFQk4PfhvFVl8Lfp0Ncm9McqwNZm5Dek0PSr0EamxHUj3CfmuMVg2PenuOWpyEYp7IQh5FdnwGVu4EQm8IWm4FRiwBTvwGWpyFVuxBegyBQk3AejxKdk3FSh1FVozMYtyBerxGTo0KdqvLdszBWt1EQvxAUm6NUo1JatuMQuzKfk8Oco1EQj3Bbl4CRt4FRqzKXg5MWmvFdj6HZt0Ean9Ldg7EVh0PXk2JUmuCSpuIWq5KTqxJQowOSu0FZq7Cat6MZp4ATn4HZq5ATo9GWgzIXj0BSk5Eer3IQu6ORvuEarxLVvzPVnyHQmuASh1GXovFQp6Bav1ORhxHYq4BWs9KRu6LVn0CaiwPYhwOShxLSp2NdpvKStyDYj4Fdn8EWrwEejyPUhwNZj6EeoyNXo7IetwJQvzDas1Ibo4NSu9Mas1PbjwFTs1Kau4MVv3GVi9Oes6HRi1ESuyIQtuGeq8CSv6JWg6NZu1AXo7AZnzLagvMfn7Des7OZs3OQv3ORh8KYhuCSqwDdhwKeq6DQkzHXv8PRi6Mdn0Nfm6MTj7HdgwHbk9NflwPQm7PZj5DWs9Nch2OQjzPegzOQmyDdtxDanuOZg0CSgzGXi6PWh2KbozDaizDfpuAfi1OYsvDUu4JXluJQh8CRo0AbswJfkwAWr1KYr0Bbj5NekuMck6Ocp1Hdg3BVvuCQv4Dar5Jet9Ocj1PXnzHam0EYt2NSv5NXp7JdmyORn6Adh7Hao9PQs3JZi5NXl2DXmyDTpxNRmxMRpwDRouIWizMVu5AStvOSv8Jen8Mfi0IfsxFdpxIRp1OSm4CWjuLVs0EasuLdqxEUruCetwIfvvBQj4KUu4HcivGcv7DTkxNUs2GRq6GSrzCah6CatwKQu6Nes9FTi2FZouBXn4KXk7IfjuIekuFRiuOfs8Odt5Kap4Fco2LQq9AVmvKan4DWs2LRp2DQu9Bag7ASp8FUn6CdmzKRgyGdu5NUs3FUl6Hfk8Ofm7LTj0AVmyOdjuJYr4NZi6PXm6FZgxFXj7DbmxMer0AZiwJSg7NUpxIeg1JdtwFQoyBXs6MchwBan8NYv9HUp4JZh8LTkvNTiwHXk2JTrxHfk6FbpwHdu7LQg9Oeu6BWp4Ibn6FfmyCWoxPRjyDbjyOUmxDaqxIeuxOUh7AXp8AVu9MWuwNcs1DWr8NWs2BYn0OVk7Bcg1PUs0HZi2Cbv0HSq5LUo1LRjyDQt6CYv6OYswJeqzNQu9MfgwFQg1Hdh9AVg0BWgyNdr9EavzDbi6Mfn4EWh2Ofm9FftxGQhwFeu0MahzFTswGWj8HWn3AWqxHWo0GQtzPco6Dfr2LUu3Ddo0PdgvGYkuPSjxBas4Dev2FQg7Hep0HZs9AXvxHat9EdhuHZqwNWmuLct6GTn9OSi4BQh1LcowGRn5BWu0PdqwPah5Lev0MQm9Man4Hcr0PYj4PQuuFTk8MYt0CTs3PUm1BUt5MdizLUr5NYn6DWozHTlxKUk0GXj3Obm2LXmvIeg9Kej9Oct8MRt6KcpwKenvIdpvDTv6Naj6Jbp5OWu9KRi9BXn0IZg9CXo5Oan9EQgwIfsxHQm3Kfp9DSvuEWn9FQiuOXn0ESp4LflzBYs3MUn8BSu7FYpwFQk2Bah3Pdi0AauvPfq1Ifu4DRpyAdu8Ebk6NRiwBShyObu0CehxAYvuPXqxDYi6Meu4GXt2DVr3LRh1HUk3KUvvFci3Cbp8NUo2Jfu2KXq0KVl9OfvwLRuxMStzGeq6Lbu8Bfp6CWs7MZv3IVp4KQn4Aao1NRl9HVj2Oft2BWs2FSn9JflyFQp3MZluEcsyDcryKXpzPTh7IRnuHev6ISovLZj1Ddt0Gbh1MQl3CVmwPSrvFSluKfm6AWkyJUl4Cfn4DVv6Acu1ERowMdg9Pbr5EQp1Gci5Dfu3GXs6MUm5KYo0PZk4KWm5Efj0KdgvDbqyCfkxOel7BWrvBci7Ifi2KRn5Nbg8KVkzCZi4KQmvMSr1BRvyBat9FZuwCXmvEfqvFVh9OXl0DZlwJUr8EUk8GRn1IYkzKer7Mbq9Fah7KTmyEdsyPTjvNQuwNbu6Pfp6Eej0CYnyGfhzHbm0DRv9FYk3DYu2NSl2Ifj6IQh8Abg6KfkuISrzAQhvHbvwLagxLbruFRnuOTm7OXmuFeu7FXo8CVn6NUtuBSh1IXq3IZvuNWn0AYl5Jav3Ndh1GQi2PUhzJUtyETl2CXgvEZsyIVl3PQt8LTv3AWk5NUj5AapxPbt8AXr5GQn9AVg8MQv9BZpzGUi3DQg6Jck4NWs0PcnuGQh5PYv1HUgwGdqyDUs6Jbl5Jen2LRhuFRrvPTg2KUr6BRu5BXivNevyEUm2KdqxDfj2BZluPSk3CUt5JTh7IVpvDWh2MXkuBTnvJco0FQp2Cen7IWjvKUsuDUr0Ido8Eao5EZh1Gbo0HZpvHQr1DYgzCWtyKdhwGUs2Peh4PekuNbrzMSi1BZi6JSk7Deu4Gah5OXj2MYsxGan1NQtvDTpzERm1Bcs3Ibl5EYs4CWt9HdqzKSgyOQh0AQl6GajxDVo0GQh5JSnuDft2BZh1Mdr1EZvwMUn8AXpwBcj6NZhzAYq7Mbp7FctxJes6Nbs2Pbj7FbjuLagzFQmvARq3DVpzPRh9ITh9OYi8KWrwEdp8NVuuESn2Dai6LUkyJYtvMSp4IYguMWj8MSo4Caq2Iel6NSl9KVp8Lfv0GchyMQr4BTiuDZk5Ich6EbkwJQt9Bav2NZhwNVt8ASh4PWr4EXg3IfizNXr9PQvwEQk1DSrwFXl9Deq5FZv8GVn7IYg6FXruCfouEVgxDfuxOfj4NZo9LUj0OTt2ARh0NVn0HYk7ISu5CYgxHSo4EZj6Ffs1KUh2FXi1LXtuJQgyNRpxKTpzIfr9BYl5GXjzGaqwPYkuBWp6Jcg5DSmuDWv2BesvJSj1HZp1Pbv6GbnvMbhzEcs4PYruLXm3CRl3Pcg0FSj0BZs6FRlvPRj4MWh3FQnwCWiyEQn2PXhuNXqzAdn3LcjuOSn4BYg3KfsuOWh1HXp0AYg4IcovMbpuNfs6NSn1Gdq5EbivNav3Pes0EesxCQvwGYqxKekyJTlzBWtzPctzDbsxGZgyCUp0PVm4ETl1JdluCXs8LXk5Dei5IQn1BdqwJfswAbp2Fep0JXn3GYtvPTo0JbsuBfnzOcmuJel2FQozLek6MapvLYnzCXt7GVmzKTo0Pfg0Caq3Ndj8FZg5Der2DfvwBWjzOUk6CWovETt6Fbu8CXg4AYu5Jfm1MTlwKYg7AWm3Jar9Gbt1Pct4Jep5ORovKRp0FUn3Efm0HYv3Fet2HRu7PWv6MVizPYn2Oei7BTuxDdluAZm2IXl3Gfj9PckzOUu2BVqzNThuLbuuCXl4NWs3DXuxIQl4MftxCQh9JckzIat9Hdj8DSg2NWg1KdsyMWt2GTr2Fcv9MQs8MbkuMYl2EYnyCSt1ASkzCTvwIdnvCdm2LahwLal2JYq5BVp0LdivIRmvMej8FfkzFbo8IXqxJWu3KWo2Gcv9Mbh9OSvwIVp3Oek9OTguPei9FSp3Han6NYi4CUkvPZnxGfpzERt2MVrzGdtwAYjvCTl1Gco7Ges1Iel6LSnvGbluFQg2CYpzDXm7IXpyNbq2CSn6NemyDQr4PZnyETvzBbs9LRh9Ddh8JYv4KdjvOZp1MbouNWhyCTp0DXq4PZh3BSpuBamuAWhuPVkzMZmuPTvuJfn0OXivKbmwGfq8KZq5JauxJfm3LZo9BYsuHQvxCak6GRo9Hbi5JWi1EWnvPRj2GZk9KWtzFRh9PXn7Eel4AXt8EcjvLZi5NZt6HRnwCdlvOekxCWqvGduzEYhxFRs7Bem4KTjzMen1LWq9KXryOWnvKdr8FUp7Gdk0EVj6OVr0BVg7Laq1GRs6LVuuJWoxOeo3Her0KYrxAWl2MUk3ITo5Dei8AXs8HdtuMekyBYgvAQi7FRu9JYs6Nes4AeqvIQoyITkwGdp6Nao7PUt6EZsuORpzEekxHVt7HQjyLUhuLUh8HeoxHYk3BRk9OTr6HbvvCbj7OavzNbg3KYq9Bcp0Abt9BflxFXv3Hau1IfguAXg5IXszKSp5Iao4BTj2Nbv8Afn9ESlxGWs5GSoxHamwFQj9Ibg6JTs7LZvyOQmwNcq5Feq0EcuyJSs5BUg8KUnxOUvwDRs7KZjuPYrzKci9CdoyIYg3Cdl5Cbi1EVn8Bcr7FTk0Odm2Cfm1HVs8NYt7CWuwBXuyAQkwKUszIavuCVlwBbryHQm0EXnzMegyGapuHYl1Hes3Hdg8AUixLZh8IStvBRv0IUp4OUqwNVq7Aeh5ORr9KduyOQo9IRq6AasvPdg6AUi1PTkuPai5NYs2ESkvNfm6Lfp2Kct0Iet0Adq0BXr1Met4Dbp7NWr6EZvxFSs9JYm1HYs7ESvzOYpuEXj5MeguHSt3Pah2Pdv9CStuHQq5IVuuJQl2Nfo5GTmxAco4NYp0GQj0MeluKVvuHSv5JRqxLYnyJfmwJUn8Ddv7IZh6AUsyBYt9LdlwFWpvHfn8KZhwBRvzNfj8NfvvPTm9FUg6Fem8EWl7ISruGfhvLei8DYt1GUjwIQq4PSo0LTv4Iek0Ebk0MXtzCdj2ObowHUs6Eeu2IVn0PVqyIViwBQg5PZs7Pbh7AatxIbq3JVlwPcm1GZgyJVg8Gft6Abn4GUo2Jek2BTv5BZgvNXj3LUjzKSs2HTm5LZmvFSt3Cfr8Abp4Jco2ESj8EQr1KcpxLZt5GSr8CfkuBRk6FZu9HRv8GWgwMZu7Gdv9DRvvFRk4MTi7KbtvLXowPesyNdj2Eem2EXk4MWt1PcuzNWl3Obh4FUg2GQu8MVg2Fct0GUoxMZpyKbv4KXnuFZj6HShyAYk8DXt6PcnwNXj9GYnxCcs3JQi7LdpuCSnyDam2IapxHWozERq1Jcv1MSo9MUhyJRs0PUm5Cbn1NfmwBTm1Gfs4AUh4NZi1Dcr8OZk4JblzOXh7NZlzAat6CegyIfg5BblzAfgzIap9BTj7Jch6EVn7LWn2DQm3BWrvMbj1BckwPVivNat6CVjuLSg2Lai9DTk7AQs3HRt8LbvxEbnwAZj2CauyOcsvIavvBdv5IanwAdn8BYluCas7ETv5IdvvPUvxDcvyIep1HRouFXp8JQt1MZkzNerzLcr1Car7Gbn6IZk7Ccl5BXp8IZr5KetvAck0AXl0NUoxLRi3Aej0Ebk5JdpvPUq9DXq0PZqyGTg5KZj4ISm4NVlwKSr6CejyATr7BRl2FVp7HVh9FZhyNSo5LftuLdk7DUhwKVk2CQl0JapuGet1Hcm0Oev8Hfg1Mav1DdkuEYnxCes6GXouEQo2JYnyIRt0AbgzCXk7MZlyKTm5Mfk8Nci4PSqwFdl5JSo8CQj5ETp9Nen3HWvvEYp3LZuyNVlyPds2PbpyIWs9HbgyOduzDbhxKXn0JTi0Pcu1DXq1JdlyFYv0EZs4KZk2Mcm4Ebk7OYr2PQj2PYl5CQtzGYk9GSm4ETp3Ler5Mbl3Beo6GclyFfl6ITk5BXo2Idm2Nbk2HTo2Pcm9NchuJYs6BckuHYh9BRt3AQg6ASl9Jbq6NYmyLfgzPbs8EYs5ETu1DZjyFZj0CWkyGQo3ITj2Har0JRi0Lbs8OTnwGepzPRh7CQgzETu4EflwBen4DVr0ORvzCat1Oeu2OdkxCag4LYowMSruFYv8IUr5DagxBbo6EYr6Ieh1Kaq6Icj2AQl5HUk9ActuMTtzOUj6Ier4IUgzATlxDRk6Nas3AUsvJdpwHep7GdlzKSvvDSjzNav9Pal5DXhvKXt2Cfv8BRm9EYm4MZt6Cev8Ffv5ARp7Ifq2FTk8LVm5KWoyEYnxFXoxCWs6MUr0PZn7HdrwMfq4Dcr0Eet4IervIWg5EQm1Fet8Fbq7MYg9MXkxMchuKYp3HUn3DYgxNYn0JcqwEfiyPXn2KXu8IYoxPWj0Feq5Lev7OXizMSjuMRm9KTqvCUs4BUj6DSvyEamwKTtxLbp7Lcm8HbvwAQjxNev0DRp6Pal9Net9AajvKQuuLQnxLfg9BWiuIeo8AcjwNVi8IZk6GYk2Hcs4GXs0HVt1CbnyASt2ATj2Mai1PWn7NXnuPcg0NQl4IUouPet3NRq9JWhwFVl6Pbt6LasyAbn8GQu6MUp4KUrvCWr5ERrzPWsxJcn2JZt9GdkvERh9Pem9KTmvEXm8OUp2OdlyDcmvEZq3ETv5Obt0EfovIfryKWvvJRl9NQr6PXp0KXs5BUkzBVr0OQp8DYgvDRn2IThxAVrvOQp0Afs1AZn2GegwJfluJcnzLbh4AZk7Fet2BUivMYtzGfgvPXi4MWl8Kcj0Ccq7JRhyAUpyKcmyMev8OTsuJRn4IQi1LVo7NZj8CZszHTl8MVh7BSsxKbk4AahyARrzLWqwLVuvAVnzASq1HVl7HViyAUkzCQrwGTp5EciwDbv9Ibp6OWpxGet8DflyJeq9EQvwOQn3IUo1GVm6Pfk3CXjuOSixGeg0FalvPfn7EXq8GXn9MQhuAQs3Ofr1LfsuGUo3LUg0Kbr5Mcm2FTj3KWg2MfkvJVpyDfq9OYr3LSu5AUl0HUo6BVh8FQg6AWkzFQp7KYp7HYnzJbmyPWt6Jdo2Jal6NVn3MQruCStuDciwFdu2Dbk8MStwNfiyKZm6Jat3CQo0BSlvHSpvFVtwKeu4JQh5BZi6Kbt0MUo9KQqzHdkxPcowLdiuJYm2Meo6GVi0GSgxOYm2GfuuJdh8MYj3NVm3BYryAYk7CWkyEWsyBYixIVs0ETg6PQu2FdtwAXruJaluJci8IRt4ORtvIQlzOSn5Iep2HSi8OUkxJak0FXhvLaq6LSnzEbv1McsvCVnwBam4LYhvAfo0Aev8Ffg1Jdn5OUtyGSqzBel5Gbm7Jeo1HVt1Hes1MbnyIfl9PbszKco4Pch6AXl7LVm5Ibj2JZg2OYpvMTm7AVq0ORjwDVtyNbv6PRsxAck9KYh3PdtxCSluLVm1EcmvGfquHSrxPVvwBfqxNfg6Ial6IYjwEYh4MRu8Jfo2BRs4Her7Jfl9AWn6EWv2Mfr2PWo5AejyHRoxAXl4Eej5Jfu7GVs1Iel5BXq1Gcj2Iap8Ebu0MVjzGYj3IWh0OTk6ORu7Keh0HVv6EQr4MQiuNal2Hdo7MatvHQu1OZpwFfl7Kcl0GTv5EXk5CYt0EStyPSs0AUk2EXmvKUpuGav3JZo6HQi0Kau8LTr4PSh4Ibl3Aaq0JWj9Aag9MXgzIYo9OZq9MUr6EVh8Hel3DTp9Afl8AQn6KRvuDVv5BTkuOSnzOVq0GWvxBbs1PXoxCcjzDRu6BQp4Ncr8Fek3Gfn6FVh4CQizJbu1BRj9NSh5Ifm4JRlyKcq6AdtxOYivLas5DfrwKfsuEcmwDZk0AYh8HYjyEQn5Iag8EUm4LVr8OXnxAcm9FWk5LXh5FYlzOWnzETi0Pdi0HYn9Gdn1CcuvIUnwBRk6JVr6NXu5PZuzJUjvBVl7EWoxASoyNbhzBVvuCdv7JTiuDXq9PVp8FWm7NamyKar6EYtvKTpuEYjzEYv8MVr5OUg4LduyFWsyEXk7PSkvLThyIdr0KbixJcu7JZszAeg6BXtwBWpzHRsxBci1LflzCZn7IXp3KbvwMfh3JZt5Map7GZkyIet1CVj4HcuyIQmvORqxDZk0GWiuMStwJZvvGfv3Bdp3KYo3PQh9Acm0IRp3ERh3Ean3IWtuAZk6IZkxJRi6EUh2KZjwObp1Bbh7DYn7Oev3DZjvAZo1AVrzMQh5CaiwPYr6DSl1Nei2Dbs6HRswDWmxPVq2IYqxNVu7JSi3Pct4HTj5DTtvMYvyPRizGSp1IfqvLWv5AVk8Obg3GQnyCWryBcr9Fak9Ceo3FbtyKThzAepxNXuwPYn7BVgyHYh0OQu0BQk5Fcr0JVlzBWk9MXm3OUtyPckwNap4Jdu6IWs9LTtuAWgzHSquGTm3Cai9FTo6AWq0EZl8CZr0GTs7Jaq8Mes1ARv2MblyCbu9BcmyNeuxERq2CXvzKeo2NSh5Odr3AVnwFWtxMdkvNanzHUixKTq4Jdl8NVuuPSl1ARoyLft2CTn2OTn7JfluHakxLYp7NRuyMTo7Idm3Dcv3KVtvITk0FRp2Jfm7GQi9GQq7MYt7JUhyKck5CUkvGRmvJfr3JWj0CXv9HYv0DTs2AUjuLYowOavwKemuFRswERlwBZnwJci5Gbh5LRo1DRp5JcqzNUu0BTr4Neq0HQr6IRuzHZp2Peh8BRk0JTkzKfsuFdi8NUm0Man4BQm0JVn5Neg6Obk1EZm3GWh5ETnvASlvDQhvEbg6OTl7Bds6ARqvCdmvNRr7ITm2LUk8Dag5LWr7FRj0CQqwIVvuAerxIelvOcn0Ndg3HZozCWm9NbrvGQsuKWq7OSrxFWu0CSg5LZkyAXs9KatxMaj6BWpuKdk5ASrxBUhxCfq5GRr4LYo4Oen6Idh8OZuxNar4NSr5FZuuLSmuFer7EWu9PYv8EegwHWnxBSm2LcquGVq6KYjzGSszNch2CTh5Kcq4GRo5Gel2Ibi4Cdh6EQp7KZhwOQrvFdv3MXs9IRl2Peh1AcvzPSiuDUl8Nfu2MRlwHen2Hfh9Jcl3PTsvDZpuBSowAan4IcoyGbpvORo7CWtwCSg9NSjzEVuuFVg3ETo4KSuyAWr7DeivHbjuAQo0FTs0Efn7ASrzBWkyAaq3CSivGfl8Aas3EaszHQnzHem8Lfm5JUswLVlzOZj4LYh8JYt2Jeh9CVr7Bap0DZs5HQt6LWquDYj5Nfr7AYk2HQtzDck2HYo7MUoxEYkzAWq0HbizEfj1PcpwBbn3Feq6KRu2Aau2BUhwIWp4DSuvJViuESk0KSv7Aeh5HTtyHTr9NQg5IZm1Abo0Hfq3AQq6EWm5Kbq4JYmwLSi7EXjxKZl8JVn5LRl3HYgwATkwJYt0EcgwIVouOYszOYt5DdpyPRtuFUjxJSp5IZkuIeh5OSj7ESn6DZhzDZk4OZr2Peh3BXuuKRu1GQhzHVi6NRryATo0OZr6Fcp1DRj2HTs8HfgyGSq5HTmvDXs1FSh4DWg4ETjuDUh4Ofi9CakuDYsvCcp3FeovBUj7KSg2EfkyJajwFZoyLfj2DRs6HVs2ESp8NXnyDVt4AUn6PSt9MVh9JQl6FTk4AanyGRp6PSr9Abs7KeqvCSu4BZg9Jas6HZr0FfowLRuuGXo1Ibm1Dbk0EZuwOVt2Fbq7KTp5PVhuOXi2CYr4NXvyDRo1Ebq1NZo7HWkwPVnzNdg3Dds2Ias2PblwPdh2MTuwCUuuGYowEZuwLSv4DXg5ATmuDVk4Aej0OTi5LfnvObi2GVqyEXrxOXlxFTv0Aal3IeiuHcg2PVr2KegyCeo4Lav7MWhxMUt8JWg4Ceg3Paj9LbhyARq9FeoyHRn7NTv4Del2EYr5IUg6IQguAViuDZlxIVi3AchwDYn3GZlvGemuAbq7NUiwJblyHatuEahuBcmzPTi2Hbv6Cdk6Bdh4HTh8NTsuLck6ETrwCQu3IYg4KWt1DYl2CYp9NToxDTjyNQo6JXi0Hdq8JRryAQnyCbi9Afj4BfvvPRk6LQowGTn5Dcn7FeruBQo1PTk8BZt3LWj5EUqwPQo4GZsvDWrzMbquDZm6AQk4HWq7BYnxITquNXj8HUq6KVhzCdsvPVs4BUq3JXn7Jeq7Bco1GTh4HWk3CRp9IQq5Lfk5FQnvAXr8CRguCQmyEYpuHVgvNZkzLRk7GZlvKcq0HZj2IZg5Idr0DZpwIdk4KfiuPZrxNbg9GSj3GRs1GQp4NUnwHQr9JRk5MfouHQr9OSj2EQsyBah4KUo8KYtvFbo3ARpzHct3MXv2OYn2KSq8HYrxMTrvNSt1MTvyPXiwNZr3NZjvJWt7Ddv4Ibl8McquDTg6BQsvAVv0Ndg8FTo3Ldg1Nco9Nbp6DSnxKYs5HWp3CXo5MUlxBatuKVt2BQr9BbizIWnvNRmxOVpwCZswFQu5AfguNTq9Mdm7GRn2ORmyPRluDdu3HSn0HVo8OSi8Jeu6MfouJfkvLUnuJTr0Dem3DanwNRl6NQu5Aeo9KRjwBZk2BRowAUjuNWl1MQg3Mck8OZm8Fas6OTq5Bdm0BQszBYuuKeh2LYluMdjwJQu6EXjxOSuuJYl9PWk0LUr1ATtyKYiyMdquAXs3Ocs5FXnuJfs5KTiyNXq6Ebk7LclyAXu4GasvITu9EVj0Bdv9Afg2Efp2Jdp5HequHXm2Cdr6LSm9Gen7Mes2PQszPcqxHfuvFUqzFbu9PWtwAXu3Ofn5IYk9FevzLTrzETr4DQo5JVm1JcmxAUpuCTt4Ccl4HRvxOeq2AcvvHQlvDYt5AQt2PXtuFam1MVqyNek1KYqxObq5CRr1Obq9EYhyPXo5HRsvASp1Odr9KRruOfi7JYh5CZluKZpuLer8OVuxAVi0BetwARl9KckxHQv9ERovBep4AVjxEYsxDfjyOeguNVnzDcs9IYguPVtxLcmyMTsuEYl9DepyCUu4Hei4HSivNVrxJSpvNRi6IftxKat1DSg1MYn5GSkyNej2JdlxKSu9BQn4IXpvFftvLVi6MXivLQg8CXtuJYj5Idv8Dbh2DfguMRvwIet6HcpwPbk7NVu7GduuHVv3MasvPTv3JZvyPfv3LRryCbgvCThzJdl6OUuuEXi0HYl2EZm4FQn3Ebl6GaQp1f7c4a5e5570921f7bc197ab297fab5820",
  aliasConfig: {
    appName: ["", "", ""],
    totalPageCount: [],
    largePageWidth: [],
    largePageHeight: [],
    normalPath: [],
    largePath: [],
    thumbPath: [],
    ToolBarsSettings: [],
    TitleBar: [],
    appLogoIcon: ["appLogoIcon"],
    appLogoLinkURL: ["appLogoLinkURL"],
    bookTitle: [],
    bookDescription: [],
    ButtonsBar: [],
    ShareButton: [],
    ShareButtonVisible: ["socialShareButtonVisible"],
    ThumbnailsButton: [],
    ThumbnailsButtonVisible: ["enableThumbnail"],
    ZoomButton: [],
    ZoomButtonVisible: ["enableZoomIn"],
    FlashDisplaySettings: [],
    MainBgConfig: [],
    bgBeginColor: ["bgBeginColor"],
    bgEndColor: ["bgEndColor"],
    bgMRotation: ["bgMRotation"],
    backGroundImgURL: ["mainbgImgUrl", "innerMainbgImgUrl"],
    pageBackgroundColor: ["pageBackgroundColor"],
    flipshortcutbutton: [],
    BookMargins: [],
    topMargin: [],
    bottomMargin: [],
    leftMargin: [],
    rightMargin: [],
    HTMLControlSettings: [],
    linkconfig: [],
    LinkDownColor: ["linkOverColor"],
    LinkAlpha: ["linkOverColorAlpha"],
    OpenWindow: ["linkOpenedWindow"],
    searchColor: [],
    searchAlpha: [],
    SearchButtonVisible: ["searchButtonVisible"],
    productName: [],
    homePage: [],
    enableAutoPlay: ["autoPlayAutoStart"],
    autoPlayDuration: ["autoPlayDuration"],
    autoPlayLoopCount: ["autoPlayLoopCount"],
    BookMarkButtonVisible: [],
    googleAnalyticsID: ["googleAnalyticsID"],
    OriginPageIndex: [],
    HardPageEnable: ["isHardCover"],
    UIBaseURL: [],
    RightToLeft: ["isRightToLeft"],
    LeftShadowWidth: ["leftPageShadowWidth"],
    LeftShadowAlpha: ["pageShadowAlpha"],
    RightShadowWidth: ["rightPageShadowWidth"],
    RightShadowAlpha: ["pageShadowAlpha"],
    ShortcutButtonHeight: [],
    ShortcutButtonWidth: [],
    AutoPlayButtonVisible: ["enableAutoPlay"],
    DownloadButtonVisible: ["enableDownload"],
    DownloadURL: ["downloadURL"],
    HomeButtonVisible: ["homeButtonVisible"],
    HomeURL: ["btnHomeURL"],
    BackgroundSoundURL: ["bacgroundSoundURL"],
    PrintButtonVisible: ["enablePrint"],
    toolbarColor: ["mainColor", "barColor"],
    loadingBackground: ["mainColor", "barColor"],
    BackgroundSoundButtonVisible: ["enableFlipSound"],
    FlipSound: ["enableFlipSound"],
    MiniStyle: ["userSmallMode"],
    retainBookCenter: ["moveFlipBookToCenter"],
    totalPagesCaption: ["totalPageNumberCaptionStr"],
    pageNumberCaption: ["pageIndexCaptionStrs"],
  },
  aliasLanguage: {
    frmPrintbtn: ["frmPrintCaption"],
    frmPrintall: ["frmPrintPrintAll"],
    frmPrintcurrent: ["frmPrintPrintCurrentPage"],
    frmPrintRange: ["frmPrintPrintRange"],
    frmPrintexample: ["frmPrintExampleCaption"],
    btnLanguage: ["btnSwicthLanguage"],
    btnTableOfContent: ["btnBookMark"],
    btnExitFullscreen: ["btnDisableFullScreen"],
    btnFullscreen: ["btnFullScreen"],
    btnHome: ["homebtnHelp"],
    btnMore: ["btnMoreOptionsLeft"],
    frmToc: ["btnBookMark"],
    frmSearch: ["btnSearch"],
    frmLinkLabel: ["lblLink"],
  },
  meta: {
    htmlTemplate: "Popular",
    theme: "Default",
    title: "01 - Giới thiệu về VN Check ",
    description: "",
    url: "https://online.fliphtml5.com/epfum/tpfb/index.html",
    pageCount: 20,
    pageWidth: 1440,
    pageHeight: 810,
    template: "Popular",
  },
  "project-config": [],
  bmtConfig: [],
  videoList: [],
  staticAd: { haveAd: false },
  language: [
    {
      language: "English",
      btnFirstPage: "First",
      btnNextPage: "Next Page",
      btnLastPage: "Last",
      btnPrePage: "Previous Page",
      btnDownload: "Download",
      btnPrint: "Print",
      btnSearch: "Search",
      btnClearSearch: "Enter key to search",
      frmSearchPrompt: "Clear",
      btnBookMark: "Table of content",
      btnHelp: "Help",
      btnHome: "Home",
      btnFullscreen: "Fullscreen",
      btnSoundOn: "Sound On",
      btnSoundOff: "Sound Off",
      btnShareEmail: "Email",
      btnSocialShare: "Social Share",
      btnZoomIn: "Zoom In",
      btnZoomOut: "Zoom Out",
      btnDragToMove: "Move by mouse drag",
      btnAutoFlip: "Auto Flip",
      btnStopAutoFlip: "Stop Auto Flip",
      btnGoToHome: "Return Home",
      frmHelpCaption: "Help",
      frmHelpTip1: "Double click to zoom in or out",
      frmHelpTip2: "Drag the page corner to view",
      frmPrintCaption: "Print",
      frmPrintBtnCaption: "Print",
      frmPrintPreparePage: "Preparing Page:",
      frmPrintPrintFailed: "Print Failed:",
      pnlSearchInputInvalid: "The search text is too short.",
      loginCaption: "Login",
      loginInvalidPassword: "Not a valid password!",
      loginPasswordLabel: "Password:",
      loginBtnLogin: "Login",
      loginBtnCancel: "Cancel",
      btnThumb: "Thumbnails",
      lblPages: "Pages:",
      lblPagesFound: "Pages:",
      lblPageIndex: "Page",
      btnAbout: "About",
      frnAboutCaption: "About & Contact",
      btnSinglePage: "Single Page",
      btnDoublePage: "Double Page",
      tipChangeLanguage: "Please select a language below...",
      btnMoreOptionsRight: "More Options",
      btnFit: "Fit Window",
      smallModeCaption: "Click to view in fullscreen",
      btnAddAnnotation: "Add Annotations",
      btnAnnotation: "Annotations",
      FlipPageEditor_SaveAndExit: "Save and Exit",
      FlipPageEditor_Exit: "Exit",
      DrawToolWindow_Redo: "Redo",
      DrawToolWindow_Undo: "Undo",
      DrawToolWindow_Clear: "Clear",
      DrawToolWindow_Brush: "Brush",
      DrawToolWindow_Width: "Width",
      DrawToolWindow_Alpha: "Alpha",
      DrawToolWindow_Color: "Color",
      DrawToolWindow_Eraser: "Eraser",
      DrawToolWindow_Rectangular: "Rectangular",
      DrawToolWindow_Ellipse: "Ellipse",
      TStuff_BorderWidth: "Border Width",
      TStuff_BorderAlph: "Border Alpha",
      TStuff_BorderColor: "Border Color",
      DrawToolWindow_TextNote: "Text Note",
      AnnotMark: "Bookmarks",
      lastpagebtnHelp: "Last page",
      firstpagebtnHelp: "First page",
      aboubtnHelp: "About",
      screenbtnHelp: "Open this application in full-screen mode",
      helpbtnHelp: "Show help",
      searchbtnHelp: "Search from pages",
      pagesbtnHelp: "Take a look at the thumbnail of this brochure",
      bookmarkbtnHelp: "Open Bookmarks",
      AnnotmarkbtnHelp: "Open Table of content",
      printbtnHelp: "Print the brochure",
      soundbtnHelp: "Turn on or off the sound",
      sharebtnHelp: "Send Email to",
      socialSharebtnHelp: "Social Share",
      zoominbtnHelp: "Zoom in",
      downloadbtnHelp: "Downdlaod this brochure",
      pagemodlebtnHelp: "Switch Single and double page mode",
      languagebtnHelp: "Switch Lauguage",
      annotationbtnHelp: "Add Annotation",
      addbookmarkbtnHelp: "Add Bookmark",
      removebookmarkbtnHelp: "Remove Bookmark",
      updatebookmarkbtnHelp: "Update Bookmark",
      btnShoppingCart: "Shopping Cart",
      Help_ShoppingCartbtn: "Shopping Cart",
      Help_btnNextPage: "Next page",
      Help_btnPrePage: "Previous page",
      Help_btnAutoFlip: "Auto filp",
      Help_StopAutoFlip: "Stop atuo filp",
      btnaddbookmark: "Add",
      btndeletebookmark: "Delete",
      btnupdatebookmark: "Update",
      frmyourbookmarks: "Your bookmarks",
      frmitems: "items",
      DownloadFullPublication: "Full Publication",
      DownloadCurrentPage: "Current Page",
      DownloadAttachedFiles: "Attached Files",
      btnCopy: "Copy Button",
      infCopyToClipboard: "Your browser does not support clipboard.",
      restorePage: "Would you like to restore your previous session?",
      tmpl_Backgoundsoundon: "Background Sound On",
      tmpl_Backgoundsoundoff: "Background Sound Off",
      tmpl_Flipsoundon: "Flip Sound On",
      tmpl_Flipsoundoff: "Flip Sound Off",
      Help_PageIndex: "The current page number",
      tmpl_PrintPageRanges: "PAGE RANGES",
      tmpl_PrintPreview: "PREVIEW",
      btnSelection: "Select Text",
      loginNameLabel: "Name:",
      btnGotoPage: "Go",
      btnSettings: "Setting",
      soundSettingTitle: "Sound Setting",
      closeFlipSound: "Close Flip Sound",
      closeBackgroundSound: "Close Backgorund Sound",
      frmShareCaption: "Share",
      frmShareLinkLabel: "Link:",
      frmShareBtnCopy: "Copy",
      frmShareItemsGroupCaption: "Social Share",
      frmPanelTitle: "Share it",
      frmShareQRcode: "QRCode",
      TAnnoActionPropertyStuff_GotoPage: "Go to page",
      btnPageBack: "Backward",
      btnPageForward: "Forward",
      SelectTextCopy: "Copy Selected Text",
      selectCopyButton: "Copy",
      TStuffCart_TypeCart: "Shopping Cart",
      TStuffCart_DetailedQuantity: "Quantity",
      TStuffCart_DetailedPrice: "Price",
      ShappingCart_Close: "Close",
      ShappingCart_CheckOut: "Checkout",
      ShappingCart_Item: "Item",
      ShappingCart_Total: "Total",
      ShappingCart_AddCart: "Add to cart",
      ShappingCart_InStock: "In Stock",
      TStuffCart_DetailedCost: "Shipping cost",
      TStuffCart_DetailedTime: "Delivery time",
      TStuffCart_DetailedDay: "day(s)",
      ShappingCart_NotStock: "Not enough in stock",
      btnCrop: "Crop",
      btnDragButton: "Drag",
      btnFlipBook: "Flip Book",
      btnSlideMode: "Slide Mode",
      btnSinglePageMode: "Single Page Mode",
      btnVertical: "Vertical Mode",
      btnHotizontal: "Horizontal Mode",
      btnClose: "Close",
      btnBookStatus: "Book View",
      checkBoxInsert: "Insert Current Page",
      lblLast: "This is the last page.",
      lblFirst: "This is the first page.",
      lblFullscreen: "Click to view in fullscreen",
      lblName: "Name",
      lblPassword: "Password",
      lblLogin: "Login",
      lblCancel: "Cancel",
      lblNoName: "User name can not be empty.",
      lblNoPassword: "Password can not be empty.",
      lblNoCorrectLogin: "Please enter the correct user name and password.",
      btnVideo: "VideoGallery",
      btnSlideShow: "SlideShow",
      btnPositionToMove: "Move by mouse position",
      lblHelp1: "Drag the page corner to view",
      lblHelp2: "Double click to zoom in, out",
      lblCopy: "Copy",
      lblAddToPage: "add to page",
      lblPage: "Page",
      lblDescription: "Title",
      lblEdit: "Edit",
      lblDelete: "Delete",
      lblRemoveAll: "RemoveAll",
      tltCursor: "cursor",
      tltAddHighlight: "add highlight",
      tltAddTexts: "add texts",
      tltAddShapes: "add shapes",
      tltAddNotes: "add notes",
      tltAddImageFile: "add image file",
      tltAddSignature: "add signature",
      tltAddLine: "add line",
      tltAddArrow: "add arrow",
      tltAddRect: "add rect",
      tltAddEllipse: "add ellipse",
      lblDoubleClickToZoomIn: "Double click to zoom in.",
      frmShareLabel: "Share",
      frmShareInfo:
        "You can easily share this publication to social networks.Just cilck the appropriate button below.",
      frminsertLabel: "Insert to Site",
      frminsertInfo:
        "Use the code below to embed this publication to your website.",
      btnQRCode: "Click to scan QR code",
      btnRotateLeft: "Rotate Left",
      btnRotateRight: "Rotate Right",
      lblSelectMode: "Select view mode please.",
      frmDownloadPreview: "Preview",
      frmDownload: "Download",
      frmHowToUse: "How To Use",
      lblHelpPage1: "Move your finger to flip the book page.",
      lblHelpPage2: "Zoom in by using gesture or double click on the page.",
      lblHelpPage3:
        "Click on the logo to reach the official website of the company.",
      lblHelpPage4:
        "Add bookmarks, use search function and auto flip the book.",
      lblHelpPage5: "Switch horizontal and vertical view on mobile devices.",
      TTActionQuiz_PlayAgain: "Do you wanna play it again",
      TTActionQuiz_Ration: "Your ratio is",
      frmTelephone: "Telephone list",
      btnDialing: "Dialing",
      lblSelectMessage: "Please copy the the text content in the text box",
      btnSelectText: "Select Text",
      btnNote: "Annotation",
      btnPhoneNumber: "Telephone",
      btnWeCharShare: "WeChat Share",
      btnMagnifierIn: "Magnifying Glass",
      btnMagnifierOut: "Magnifier Reduction",
      frmShareSmallProgram: "smallProgram",
      btnMagnifier: "Magnifier",
      frmPrintPrintLimitFailed: "Sorry, you can't print the pages.",
      infNotSupportHtml5:
        "HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.",
      btnReport: "Report",
      btnDoubleSinglePage: "Page switch",
      btnDownloadPosterPrompt: "Click to download the poster",
      infLongPressToSavePoster:
        "Press and hold the mobile terminal to save the poster",
      infLongPressToIndentify: "Long press to identify QR code",
      infScanCodeToView: "Scan code to read",
      frmaboutcaption: "Contact",
      frmaboutDESCRIPTION: "Description",
      frmaboutAUTHOR: "Author",
      frmaboutADDRESS: "Address",
      frmaboutEMAIL: "Email",
      frmaboutWEBSITE: "Website",
      frmaboutMOBILE: "Mobile",
      infDeleteNote: "Do you want to delete the note?",
      proFullScreenWarn:
        "Current browser does not support full-screen,Please use Chrome for best results",
      btnBack: "Backs",
      frmVideoListTitle: "Video list",
      frmVideoTitle: "Video",
      lblConfirm: "Confirm",
      frmBookMark: "Book Mark",
      btnExitFullscreen: "Exit fullscreen",
      btnMore: "More",
      frmPrintall: "Print All Pages",
      frmPrintcurrent: "Print Current Page",
      frmPrintRange: "Print Range",
      frmPrintexample: "Example: 2,3,5-10",
      frmPrintbtn: "Print",
      frmaboutcontactinformation: "Contact Information",
      frmSearch: "Search",
      frmToc: "Table of Contents",
      btnTableOfContent: "Show Table of Contents",
      frmLinkLabel: "Link",
      frmQrcodeCaption:
        "Scan the bottom two-dimensional code to view with mobile phone.",
      btnLanguage: "Change Language",
      msgConfigMissing:
        "Configuration file is missing, unable to open the book.",
      lblSave: "Save",
      accessRestrictedTitle: "Access Restricted",
      enterYourName: "Enter your name",
      enterVisitCode: "Please enter your password",
      enterReadingCode: "enter your reading code",
      enterTheReason: "Enter your reason for application",
      enterPhoneNumber: "Enter your email address",
      enterVerificationCode: "Enter your verification code",
      getVerificationCode: "Send",
      sendValidCodeSuccess: "Verification code sent",
      getVerificationCodePrompt: "Get a verification code sent to your email",
      enterPasswordPrompt: "Password required to proceed reading",
      leaveMsgSimilarBooks: "Explore More Books",
      leaveMsgToAuthor: "Contact Author",
      leaveMsgName: "Your Name",
      leaveMsgContact: "Your Contact Information (visible only to the author)",
      leaveMsgEnter: "Please Enter the Message",
      leaveMsgCancel: "Cancel",
      leaveMsgCommitTitle: "Submit",
      leaveMsgPrompt: "We will forward your message to the book uploader.",
      leaveMsgErrorPrompt: "Exception occurred. Please try again later",
      readingCodeErrorPrompt: "Invalid reading code. Please try again",
      passwordErrorPrompt: "Invalid password. Please try again",
      invalidPhoneNumber: "Invalid number. Please try again",
      invalidEmail: "Invalid Email. Please try again",
      verificationCodeErrorPrompt:
        "Invalid verification code. Please try again",
      codeSendingFrequent: "Frequent operation, please try again later",
      commiteTitle: "Verify",
      shamStopTitle:
        "The author's account privileges have resulted in book access suspension.",
      shamStopSubTitle:
        "Contact <a target='_blank' href='{%host}/homepage/{%uLink}/' style='text-decoration: underline' >the author</a> for further information.",
      shamStopLeavePrompt: "Please complete the question.",
      shamStopLeaveMsgSuccessPrompt: "Send successfully",
      codeSending: "Sending",
      viewFullScreen: "Fullscreen",
      cardsSign: "click to view card",
      frmaboutViews: "Views",
      btnMessage: "Message",
      btnInstructions: "instructions",
      btnArticlePages: "Pages",
      btnArticleList: "Articles",
      btnCalendar: "Calendar",
      btnBook: "Book",
      btnEnlarge: "Enlarge",
      btnReduce: "Reduce",
      btnPrevArticle: "Prev Article",
      btnNextArticle: "Next Article",
      copySuccessfully: "Copy Successfully",
      cardsWechat: "Wechat",
      cardsTelephone: "phone",
      close: "close",
      jumpPageByEnterNumber:
        "Enter the page number to jump quickly to the specified page",
      jump: "Jump",
      relatedContent: "related information",
      brandTitleUndefined: "No brand name is set yet",
      more: "More",
      fold: "Put away",
      otherWorks: "other works",
      flipSound: "page turning sound",
      backgroundSound: "Background music",
      report: "report",
      copySuccessTip: "copy successfully",
      saveSuccessTip: "Saved successfully",
      scanCodeAddMy: "After saving, WeChat scan the code and add my friend",
      saveImg: "save Picture",
      searchTheBook: "Search this book content",
      historicalRecord: "history record",
      searchResultCount: "A total of {%count} results",
      noRelevantResults: "No relevant results",
      changeTheKeyWords: "Try another keyword ~",
      leastWordsTip: "Please enter at least 2 words",
      jumpPageInputTip:
        "Enter the page number to jump quickly to the specified page",
      jumpto: "Jump to",
      foldThumbnailTip: "Click here to put away the thumbnail ~",
      btnLoadingText: "In loading, it's fine soon",
      btnTitleText: "Read now",
      relatedInfoText: "Related Information",
      brandContactFrTitle: "Contact the author",
      shareFromPage: "Share starting from page N",
      TStuffShowInformatin_Width: "Background width",
      TStuffShowInformatin_Height: "Background height",
      TPageList_BlankPage: "Blank page",
      morePanelBookLink: "Link",
      morePanelPoster: "Poster",
      morePanelOtherShare: "Other",
      doublePageTitle: "Rotate the phone to enable double-page reading mode",
      doublePageDescription: "How to set landscape ?",
      doublePageGotIt: "Got it",
      doublePageAndroidSettingStep1: "1.The phone allows auto-rotation",
      doublePageAndroidSettingStep2:
        "2.The browser for reading e-books needs to be set to allow horizontal screen",
      doublePageAndroidSettingStep3:
        "3.Reading books with mobile phone turned sideways",
      doublePageIPhoneSettingStep1: "1.Phone portrait orientation lock off",
      doublePageIPhoneSettingStep2:
        "2.Reading books with mobile phone turned sideways",
      noFilesAvailablePrompt: "No Files Available!",
    },
  ],
  ols: [],
  slideshow: [],
  pageEditor: [],
  flipByAudio: null,
  downloadconfig: {
    pdf: null,
    isDownloadProject: false,
    isDownloadAttach: false,
    attachments: [],
    hideDownloadSinglePage: false,
  },
  assistantConfig: null,
  phoneNumber: [],
  bookPlugin: null,
  fliphtml5_pages: [
    {
      n: ["2b568094b00aeda4ef70532eacba93f7.webp"],
      t: "./files/thumb/d55a4b805a62ef622245f80a99c7edea.webp",
    },
    {
      n: ["5b23b565768b844247f3a70355eff28f.webp"],
      t: "./files/thumb/aca52581eba89cbc4b181a9d4851ec9a.webp",
    },
    {
      n: ["da8aa501b25bab0fea96436566d3be73.webp"],
      t: "./files/thumb/90db5ee55ca674c38742fb43304932c5.webp",
    },
    {
      n: ["a8a204e4b188540da1b0865c64f3b3f2.webp"],
      t: "./files/thumb/9d6f46f26fdfc59cd2b5c78165453a05.webp",
    },
    {
      n: ["7f0e346aad28001bc8ddab7364cf26a1.webp"],
      t: "./files/thumb/4c4e0599e06fa34b11280daf3cc17cd9.webp",
    },
    {
      n: ["d132677a8faf14f5304942e43cd0d273.webp"],
      t: "./files/thumb/a88cbaa498a98e9cb702ed4ce64628f5.webp",
    },
    {
      n: ["9ebe2f6f9afa4f4f668e0be99513d0b7.webp"],
      t: "./files/thumb/c7cdbd432f987db6fadbdd0312afa17d.webp",
    },
    {
      n: ["c7e2125371f03fa18886716a08a655cb.webp"],
      t: "./files/thumb/5e8803192b8545b97918941e95c99c53.webp",
    },
    {
      n: ["7e293a2a3e9174ccf554105608913be2.webp"],
      t: "./files/thumb/be71abf11c055660df91ef4cfc01d1dc.webp",
    },
    {
      n: ["5389e820a89c79d8d73e93354ba865dc.webp"],
      t: "./files/thumb/7503623df9e67be8f50d473c9be45e01.webp",
    },
    {
      n: ["5666e2d3c170404825af351cc19a6d51.webp"],
      t: "./files/thumb/579c3c7ff2df392da57a6c9c4c2123fd.webp",
    },
    {
      n: ["c8abddfba2134c9b36b8d0e6b6f7bf5d.webp"],
      t: "./files/thumb/57f35806e5d2cb92add548f21101b28b.webp",
    },
    {
      n: ["4ab8605836841dc8d3f488edc7f457af.webp"],
      t: "./files/thumb/7fbd1f3bb7eca0a8737b8e778ebae77d.webp",
    },
    {
      n: ["804521c0e124fcd8d2550562e3c9353c.webp"],
      t: "./files/thumb/4239301d5e2436f479bffef94d24baaf.webp",
    },
    {
      n: ["8712bfda0124f536a91eb231a0f44b1c.webp"],
      t: "./files/thumb/47e3b9bd383be7d4c54dae0410106325.webp",
    },
    {
      n: ["ac59a73b126212d2f271413b08b52aa9.webp"],
      t: "./files/thumb/52e70da14ae6ce0ee981735e802d150d.webp",
    },
    {
      n: ["87da3d377eef335aaef5d2ac9bab9ed1.webp"],
      t: "./files/thumb/2489b05b4bb5f8e6dc77f5364bb1f80c.webp",
    },
    {
      n: ["958dd216943a40cf2c087af68c79037e.webp"],
      t: "./files/thumb/8f6ef63033a61a4024d97c38ba1735a8.webp",
    },
    {
      n: ["b5abe4e4b56ac89ef74c221c128eacf4.webp"],
      t: "./files/thumb/bb971574ef20ca4de8c55e19ea3095f4.webp",
    },
    {
      n: ["e8b13ba0bbc472af785e0f4a8ca3c646.webp"],
      t: "./files/thumb/5fba7ea3a7c630f073116bb72bea8361.webp",
    },
  ],
  downloadConfig: null,
  fileExist: { pageEditor: 0, plugin: 0 },
  loadingConfig: {
    loadingBackground: "#323232",
    loadingCaptionColor: "#DDDDDD",
    loadingCaption: "",
    loadingCaptionFontSize: "20",
    loadingPicture: "",
    loadingPictureHeight: "150",
    showLoadingGif: "Yes",
    loadingVideo: "",
    loadingDisplayTime: "0",
  },
};
